<div class="alert alert-block alert-warning">
<b>BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS</b>
</div>

<div class="alert alert-block alert-success">
<b>BROADCASTING AND ARRAY SUMMATION</b>
</div>

In [1]:
import numpy as np

In [3]:
A = [[1, 2, 3], [4, 5, 6], [7, 8,9]]
print(np.sum(A, axis=None))

45


In [6]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.sum(A, axis = 0))
print(np.sum(A, axis = 0).shape)

[12 15 18]
(3,)


In [7]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1).shape)

[ 6 15 24]
(3,)


In [9]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.sum(A, axis = 0, keepdims = True))

[[12 15 18]]


In [10]:
print(np.sum(A, axis = 0,keepdims = True).shape)

(1, 3)


In [11]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.sum(A, axis = 1,keepdims = True))

[[ 6]
 [15]
 [24]]


In [12]:
print(np.sum(A, axis = 1,keepdims = True).shape)

(3, 1)


In [14]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.max(A, axis = 0))

[7 8 9]


In [17]:
A = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8,9]
    ]
print(np.max(A, axis = 1))

[3 6 9]


<div class="alert alert-block alert-success">
<b>ACTIVATION FUNCTION: RELU</b>
</div>

In [ ]:
import numpy as np
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
# Compare two arrays and return a new array containing the element-wise maxima
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [2]:
# ReLU activation
class Activation_ReLU:
 # Forward pass
 def forward(self, inputs):
 # Calculate output values from input
  self.output = np.maximum(0, inputs)

<div class="alert alert-block alert-success">
<b>DENSE LAYER CLASS</b>
</div>

In [4]:
# Dense layer
class Layer_Dense:
 # Layer initialization
 def __init__(self, n_inputs, n_neurons):
 # Initialize weights and biases
   self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
   self.biases = np.zeros((1, n_neurons))

 # Forward pass
 def forward(self, inputs):
 # Calculate output values from inputs, weights and biases
   self.output = np.dot(inputs, self.weights) + self.biases

<div class="alert alert-block alert-success">
<b>GENERATING NON LINEAR TRAINING DATA</b>
</div>

In [5]:
from nnfs.datasets import spiral_data

In [6]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Make a forward pass of our training data through this layer
dense1.forward(X)
# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.output)
# Let's see output of the first few samples:
print(activation1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.78636767e-05 8.90856953e-05 0.00000000e+00]
 [1.54787111e-04 1.74920817e-04 0.00000000e+00]
 [2.97947818e-04 2.24089705e-04 0.00000000e+00]
 [9.18502286e-05 3.35852092e-04 0.00000000e+00]]


<div class="alert alert-block alert-success">
<b>ACTIVATION FUNCTION: SOFTMAX</b>
</div>

In [8]:
inputs = [
    [1, 2, 3, 2.5],
    [2., 5., -1., 2],
    [-1.5, 2.7, 3.3, -0.8]
        ]

# Get unnormalized probabilities
exp_values = np.exp(inputs - np.max(inputs, axis=1,keepdims=True))
 # Normalize them for each sample
probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
print(probabilities)
np.sum(probabilities, axis = 1)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


array([1., 1., 1.])

In [9]:
# Softmax activation
class Activation_Softmax:
 # Forward pass
 def forward(self, inputs):
 # Get unnormalized probabilities
  exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
 # Normalize them for each sample
  probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
  self.output = probabilities

In [15]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)

In [ ]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values
dense2 = Layer_Dense(3, 3)
# Create Softmax activation (to be used with Dense layer):
activation2 = Activation_Softmax()

In [18]:
# Make a forward pass of our training data through this layer
dense1.forward(X)
# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

In [19]:
# Make a forward pass through second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)
# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)
# Let's see output of the first few samples:
print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33333282 0.33333375 0.33333343]
 [0.33333269 0.33333402 0.33333329]
 [0.33333287 0.333334   0.33333312]
 [0.33333141 0.33333503 0.33333356]]
